apiVersion: v1
kind: Service
metadata:
  name: gamebot
  labels:
    name: gamebot    
spec:
  selector:
    name: gamebot    
  type: LoadBalancer
  ports:
   - port: 80
     name: gamebot
     targetPort: 8080
     protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamebot
spec:
  replicas: 10
  selector:
    matchLabels:
      name: gamebot      
  minReadySeconds: 5
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: gamebot        
    spec:
      imagePullSecrets:
        - name: teamregistry
      containers:
      - name: gamebot
        image: t9xtacrbbe292.azurecr.io/gamebot:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: gamebot         
            protocol: TCP
        env: 
          - name: "PORT"
            value: "8080"
          - name: "PICK_STRATEGY"
            value: "RANDOM"
          - name: "APPINSIGHTS_INSTRUMENTATIONKEY"
            value: "424c14d1-1bff-4451-9985-6a800ad9762f"
          - name: "FF_BETS"
            value: "1"
        livenessProbe:
          exec:
            httpGet:
              path: /health
              port: 8080
              
